### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by Traf27**
Hey,

its few improvements, 
I have not upgraded version in manifest etc.
Cherrypick commmits that you like :)

I don't know how to instantialize new js objects in scalajs.  There are some plugins for slickgrid, like [AutoColumnSize](https://github.com/naresh-n/slickgrid-column-data-autosize), that i'd like to try but to initialize plugin, I have to pass it like that (code from example in JS from plugin author )
```
grid.registerPlugin( new Slick.AutoColumnSize() ) 
```
And i have no clue how to make it from scala.
```
// some code from looty states :
grid = js.Dynamic.newInstance(global.Slick.Grid)("#grid", dataView, columns.getJsAy(), options)
//so i could probably...
grid.registerPlugin( <what-to-put-here?> )
```
Also I wish that I knew how to use PoeCacherChrome to store data between downtimes.
Maps also could be read from there, as they are making pull request all over again.

Cheers

### CODE REVIEW

**Comment by AnnanFay** [comment]
I really like the idea of having an 'unparsed' column. It's a good failsafe since no matter how much work is done there will always be the potential for stuff which passes through the filters.

I have started using the above PR's branch and will post if I find any issues.

**Comment by Traf27** [comment]
> I really like the idea of having an 'unparsed' column. It's a good failsafe since no matter how much work is done there will always be the potential for stuff which passes through the filters.
> 
> I have started using the above PR's branch and will post if I find any issues.

**Comment by Traf27** [comment]
1.

**Comment by Traf27** [comment]
> I really like the idea of having an 'unparsed' column. It's a good failsafe since no matter how much work is done there will always be the potential for stuff which passes through the filters.
> 
> I have started using the above PR's branch and will post if I find any issues.

Thank you!

I found that some of parsers are made for affixes, but never used in SelectColumns or anywhere else. So it was making unparsed column less useful.

I'll try to add it with your proposed chance to dodge etc.

**Review by benjaminjackman — APPROVED** [review]
This looks pretty good to me

**Pull request merged**
